<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.4.363
*/

require_once('form_process.php');

$form = array(
	'subject' => '名称未設定 5 フォーム の送信',
	'heading' => '新規フォームの送信',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'チェック済み',
		'checkbox_unchecked' => '未チェック',
		'submitted_from' => 'Web サイトから送信されたフォーム : %s',
		'submitted_by' => '訪問者の IP アドレス : %s',
		'too_many_submissions' => '最近、この IP からの送信回数が多すぎます',
		'failed_to_send_email' => '電子メールの送信に失敗しました',
		'invalid_reCAPTCHA_private_key' => '無効な reCAPTCHA プライベートキーです。',
		'invalid_reCAPTCHA2_private_key' => '無効な reCAPTCHA 2.0 プライベートキーです。',
		'invalid_reCAPTCHA2_server_response' => '無効な reCAPTCHA 2.0 サーバー応答です。',
		'invalid_field_type' => '不明なフィールドの種類「%s」です。',
		'invalid_form_config' => 'フィールド「%s」には無効な設定が含まれています。',
		'unknown_method' => '不明なサーバー要求メソッド'
	),
	'email' => array(
		'from' => 'takumawatanabe82@gmail.com',
		'to' => 'takumawatanabe82@gmail.com'
	),
	'recaptcha2' => array(
		'private_key' => 'null'
	),
	'fields' => array(
		'custom_U7791' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '大深 譲さんの評判',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「大深 譲さんの評判」が必要です。'
			)
		),
		'g-recaptcha-response' => array(
			'order' => 2,
			'type' => 'recaptcha2',
			'label' => '画像認証',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「画像認証」が必要です。',
				'format' => 'reCAPTCHA 2.0 値が正しくありません。'
			)
		)
	)
);

process_form($form);
?>
